const cases=[['iran','Iran','Nuclear monitoring and social-source review',86],['sudan','Sudan','Humanitarian and conflict-source monitoring',72],['gaza','Gaza spillover','Regional spillover and source landscape',69],['ukraine','Ukraine Donbas','OSINT, map and civil-society sources',78],['redsea','Red Sea Yemen','Shipping, maritime risk and Yemen context',74],['sahel','Sahel','Regional instability and humanitarian sources',67]];
const langs=['nl','en','de','fr','es','pt','ar','fa','ur','hi','bn','id','ja','zh','ru'];
const labels={nl:['Dashboard','Cases','GEO','Review Queue','Rapporten','Instellingen'],en:['Dashboard','Cases','GEO','Review Queue','Reports','Settings'],de:['Dashboard','Fälle','GEO','Review Queue','Berichte','Einstellungen'],fr:['Tableau','Cas','GEO','File de revue','Rapports','Paramètres'],es:['Panel','Casos','GEO','Revisión','Informes','Ajustes'],pt:['Painel','Casos','GEO','Revisão','Relatórios','Configurações'],ar:['لوحة','قضايا','جيو','المراجعة','تقارير','إعدادات'],fa:['داشبورد','پرونده‌ها','جغرافیا','بازبینی','گزارش‌ها','تنظیمات'],ur:['ڈیش بورڈ','کیسز','جیو','ریویو','رپورٹس','ترتیبات'],hi:['डैशबोर्ड','केस','GEO','समीक्षा','रिपोर्ट','सेटिंग'],bn:['ড্যাশবোর্ড','কেস','GEO','রিভিউ','রিপোর্ট','সেটিং'],id:['Dasbor','Kasus','GEO','Review','Laporan','Pengaturan'],ja:['ダッシュボード','ケース','GEO','レビュー','レポート','設定'],zh:['仪表盘','案例','GEO','审核','报告','设置'],ru:['Панель','Кейсы','GEO','Проверка','Отчеты','Настройки']};
const st={route:'dashboard',caseId:'iran',lang:localStorage.ll_lang||'nl',obs:'obs-1'};
function t(i){return (labels[st.lang]||labels.nl)[i]||labels.nl[i]}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function current(){return cases.find(c=>c[0]===st.caseId)||cases[0]}
function shell(){document.documentElement.lang=st.lang;document.body.classList.toggle('rtl',['ar','fa','ur'].includes(st.lang));document.getElementById('app').innerHTML=`<div class="app" data-ui-version="3.0.1"><aside class="side"><div class="brand"><img src="assets/brand/legolens-icon.svg" alt=""><div><b>LegoLens</b><br><small>v3.0.1 runtime</small></div></div><nav class="nav">${['dashboard','cases','geo','review','reports','settings'].map((r,i)=>`<button class="${st.route===r?'active':''}" data-route="${r}">${t(i)}</button>`).join('')}</nav><div class="sidecard"><b>${esc(current()[1])}</b><p class="muted">${esc(current()[2])}</p><div class="progress"><span style="width:${current()[3]}%"></span></div></div></aside><main><header class="top"><input class="search" placeholder="Search sources, cases, observations"><div class="actions"><select id="lang">${langs.map(l=>`<option ${l===st.lang?'selected':''}>${l}</option>`).join('')}</select><button class="btn primary" data-route="review">Open review</button><div class="avatar">A</div></div></header>${page()}</main></div>`;bind()}
function hero(title,sub){return `<section class="hero"><div><span class="badge dark">Command Center Hybrid</span><h1>${title}</h1><p>${sub}</p><button class="btn primary" data-route="cases">Open cases</button> <button class="btn" data-route="geo">Open GEO</button></div><div class="kpis">${kpi('Cases',cases.length,'active')}${kpi('Sources',196,'candidate-first')}${kpi('Reviews',24,'open')}${kpi('Readiness','74%','portfolio')}</div></section>`}
function kpi(a,b,c){return `<div class="kpi"><strong>${b}</strong><small>${a}</small><br><small>${c}</small></div>`}
function page(){if(st.route==='cases')return casePage();if(st.route==='geo')return geoPage();if(st.route==='review')return reviewPage();if(st.route==='reports')return reportsPage();if(st.route==='settings')return settingsPage();return dashboard()}
function dashboard(){return hero('LegoLens 3.0.1','Een lichte runtime-interface voor case intelligence, GEO-observaties, review en rapportage.')+`<section class="grid cols">${cases.map(c=>caseCard(c)).join('')}</section><section class="grid two" style="margin-top:18px"><div class="card"><h3>Activiteitenoverzicht</h3>${['Nieuwe observatie gekoppeld aan Iran','GEO marker geselecteerd','Review item bijgewerkt','Rapportconcept gegenereerd'].map(x=>`<p>• ${x} <span class="muted">Vandaag</span></p>`).join('')}</div><div class="card"><h3>Status & paraatheid</h3><p class="badge green">Alle systemen operationeel</p><p class="muted">Runtime-only branch zonder docs, screenshots of historische builds.</p></div></section>`}
function caseCard(c){return `<article class="card case-card"><div class="visual"></div><div class="case-body"><span class="badge">${c[3]}% readiness</span><h3>${esc(c[1])}</h3><p class="muted">${esc(c[2])}</p><div class="progress"><span style="width:${c[3]}%"></span></div><br><button class="btn primary" data-case="${c[0]}" data-route="cases">Open</button> <button class="btn" data-case="${c[0]}" data-route="geo">GEO</button></div></article>`}
function casePage(){const c=current();return `<section class="grid two"><div>${hero(c[1]+' case dashboard',c[2])}<div class="tabs">${['Overzicht','Observaties','Locaties','Bronnen','Tijdlijn','Notities'].map((x,i)=>`<button class="tab ${i?'':'active'}">${x}</button>`).join('')}</div><div class="card"><h3>Samenvatting</h3><p>Casusgericht dossier met broncontext, observaties, GEO-koppelingen, taxatie en reviewstatus.</p></div><div class="card"><h3>Recente observaties</h3><div class="strip">${[1,2,3,4,5,6].map(i=>thumb('OBS-'+String(i).padStart(3,'0'),'Vandaag')).join('')}</div></div></div><aside class="card"><h3>Kerninformatie</h3><p><b>Eigenaar</b><br>Analist</p><p><b>Prioriteit</b><br><span class="badge red">Hoog</span></p><p><b>Status</b><br><span class="badge green">Actief</span></p><p><b>Voortgang</b></p><div class="progress"><span style="width:${c[3]}%"></span></div></aside></section>`}
function thumb(a,b){return `<button class="thumb ${st.obs===a?'active':''}" data-obs="${a}"><div class="thumbpic"></div><p><b>${a}</b><br><span class="muted">${b}</span></p></button>`}
function geoPage(){return `<section class="grid two"><div class="card"><h3>GEO kaart</h3><div class="map">${[[22,30,1],[55,42,2],[68,65,3],[35,70,4]].map(p=>`<button class="pin ${st.obs==='obs-'+p[2]?'active':''}" style="left:${p[0]}%;top:${p[1]}%" data-obs="obs-${p[2]}"><span>${p[2]}</span></button>`).join('')}</div><h3>Observaties in gebied</h3><div class="strip">${[1,2,3,4,5,6].map(i=>thumb('obs-'+i,'GEO observatie')).join('')}</div></div><aside class="card"><h3>Locatie details</h3><p><b>Geselecteerd</b><br>${esc(st.obs)}</p><p class="muted">Marker, preview en detailpaneel gebruiken dezelfde observatie-id.</p><button class="btn primary">Open in case</button></aside></section>`}
function reviewPage(){const rows=[['Hoog','OBS-0831','Camera','Open'],['Hoog','OBS-0830','Beeld','Open'],['Midden','OBS-0829','Analyse','In review'],['Laag','DOC-1122','Document','Open']];return `<section class="grid two"><div class="card"><h3>Review Queue</h3><table class="table"><thead><tr><th>Prioriteit</th><th>ID</th><th>Type</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td><span class="badge ${r[0]==='Hoog'?'red':r[0]==='Midden'?'amber':'green'}">${r[0]}</span></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div><aside class="card"><h3>Detail</h3><div class="thumbpic" style="border-radius:18px"></div><p><b>OBS-0831</b><br>Voertuigobservatie</p><button class="btn primary">Open in case</button> <button class="btn">Markeer afgehandeld</button></aside></section>`}
function reportsPage(){return `<section class="card"><h3>Rapporten</h3><p>Executive summary, GEO-overzicht, observaties, taxatie, onzekerheden en evidence appendix.</p><button class="btn primary">Genereer rapport</button></section>`}
function settingsPage(){return `<section class="card"><h3>Instellingen</h3><p>Runtime settings, taal, connectors, review policy en exportregels.</p><p><span class="badge green">3.0.1 runtime-only</span></p></section>`}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{if(b.dataset.case)st.caseId=b.dataset.case;st.route=b.dataset.route;shell()});document.querySelectorAll('[data-obs]').forEach(b=>b.onclick=()=>{st.obs=b.dataset.obs;shell()});document.getElementById('lang').onchange=e=>{st.lang=e.target.value;localStorage.ll_lang=st.lang;shell()}}
shell();
