(() => {
  'use strict';
  const $ = (sel, root = document) => root.querySelector(sel);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
  const api = async (path, options = {}) => {
    const res = await fetch(path, options);
    if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
    const type = res.headers.get('content-type') || '';
    return type.includes('json') ? res.json() : res.text();
  };
  const state = { appData: { case_packs: [] }, sourceSet: { sources: [], source_families: [] }, candidates: [], activeCase: 'iran' };
  const attribution = 'Repository -> Case -> Source family -> Source -> Platform -> Narrative -> Item -> Review state';
  const reviewStates = ['candidate', 'triaged', 'needs_evidence', 'linked_to_claim', 'reviewed', 'rejected', 'share_blocked', 'share_approved'];
  function toast(message) { const el = $('#toast'); if (!el) return; el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
  async function loadData() {
    try { state.appData = await api('/api/app-data'); } catch { state.appData = await fetch('data/app_data.json').then(r => r.json()).catch(() => ({ case_packs: [] })); }
    try { state.sourceSet = await api('/api/source-set'); } catch { state.sourceSet = await fetch('data/source_set.json').then(r => r.json()).catch(() => ({ sources: [], source_families: [] })); }
    try { state.candidates = (await api('/api/ingestion/candidates')).candidates || []; } catch { state.candidates = []; }
    state.activeCase = state.appData.case_packs?.[0]?.id || 'iran';
  }
  const countSources = (caseId) => (state.sourceSet.sources || []).filter((s) => (s.case_ids || []).includes(caseId)).length;
  function badge(text) { return `<span class="badge">${esc(text)}</span>`; }
  function candidateCard(c) { return `<article class="card"><div class="body"><div>${badge(c.review_status || 'candidate')}${badge(c.fetch_status || 'metadata')}</div><div class="title">${esc(c.title || c.source_name || c.id)}</div><small>${esc(c.case_id || '')} · ${esc(c.source_name || c.source_id || '')}</small><p class="muted">${esc(c.attribution_chain || attribution)}</p></div></article>`; }
  function shell() {
    $('#app').innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><div class="logo">LL</div><div><h1>LegoLens Core</h1><small>v3.0.0 final local release</small></div></div><nav class="nav"><a href="#overview">Overview</a><a href="#content-updates">Content Updates</a><a href="#media-library">Media Library</a><a href="#graph-stats">Graph Stats</a><a href="#investigate">Investigate</a><a href="#review">Review</a><a href="#reports">Reports</a><a href="#admin">Admin Settings</a></nav><div class="sidebar-footer"><button class="btn btn-red" data-action="run-all">Sync all projects</button><small>candidate-only · review-first</small></div></aside><main class="main"><header class="topbar"><input class="search" placeholder="Search sources, candidates, cases"><button class="btn" data-action="refresh">Refresh</button><button class="btn btn-red" data-action="run-all">Run all ingestion</button></header><section id="overview" class="section"></section><section id="content-updates" class="section"></section><section id="media-library" class="section"></section><section id="graph-stats" class="section"></section><section id="investigate" class="section"></section><section id="review" class="section"></section><section id="reports" class="section"></section><section id="admin" class="section"></section></main></div>`;
    renderAll();
  }
  function renderAll() { renderOverview(); renderContentUpdates(); renderMediaLibrary(); renderGraphStats(); renderInvestigate(); renderReview(); renderReports(); renderAdmin(); }
  function renderOverview() {
    const cases = state.appData.case_packs || [];
    $('#overview').innerHTML = `<div class="hero"><div class="hero-content"><div class="kicker">Review-first local intelligence workspace</div><h2>LegoLens Core v3.0.0</h2><p>Persistent candidates, audit trail, legacy import, Media Library attribution and local exports. All ingestion remains candidate-only until analyst review.</p><div class="metrics"><div class="metric"><b>${cases.length}</b><small>case packs</small></div><div class="metric"><b>${state.sourceSet.sources?.length || 0}</b><small>source records</small></div><div class="metric"><b>${state.candidates.length}</b><small>runtime candidates</small></div></div></div></div><div class="panel"><h3>Case packs</h3><div class="case-tabs">${cases.map((c) => `<button class="case-tab ${c.id === state.activeCase ? 'active' : ''}" data-case="${esc(c.id)}">${esc(c.title || c.id)} <small>${countSources(c.id)} sources</small></button>`).join('')}</div></div>`;
  }
  function renderContentUpdates() { $('#content-updates').innerHTML = `<div class="panel"><div class="between"><div><h2>Content Updates</h2><p class="muted">Run single-case or all-project source sync. Output remains candidate-only.</p></div><button class="btn btn-red" data-action="run-all">Sync all projects</button></div><div class="codebox">POST /api/ingestion/run-all\n{ "limit_per_case": 40 }</div><div class="grid">${state.candidates.slice(0, 12).map(candidateCard).join('') || '<p class="muted">No runtime candidates yet.</p>'}</div></div>`; }
  function renderMediaLibrary() { const rows = (state.candidates.length ? state.candidates : state.sourceSet.sources || []).slice(0, 16); $('#media-library').innerHTML = `<div class="panel"><h2>Media Library</h2><p class="muted">Source records show source, platform, status, URL status and attribution chain.</p><div class="table-wrap"><table class="table"><thead><tr><th>Source</th><th>Platform</th><th>Status</th><th>Attribution</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${esc(r.source_name || r.name || r.source_id)}</td><td>${esc(r.platform || 'source')}</td><td>${esc(r.fetch_status || r.review_status || r.status || 'candidate')}</td><td>${esc(r.attribution_chain || attribution)}</td></tr>`).join('')}</tbody></table></div></div>`; }
  function renderGraphStats() { const cases = state.appData.case_packs || []; $('#graph-stats').innerHTML = `<div class="panel"><h2>Graph Stats</h2><p class="muted">Dataset and attribution coverage across case packs.</p><div class="metrics">${cases.map((c) => `<div class="metric"><b>${countSources(c.id)}</b><small>${esc(c.title || c.id)} source records</small></div>`).join('')}</div><p class="muted attr-chain">${attribution}</p></div>`; }
  function renderInvestigate() { $('#investigate').innerHTML = `<div class="panel"><h2>Investigate</h2><p class="muted">Trace a source or candidate through case, source family, platform, narrative, item and review state.</p><div class="codebox">${attribution}</div></div>`; }
  function renderReview() { $('#review').innerHTML = `<div class="panel"><h2>Review</h2><p class="muted">Review states: ${reviewStates.join(', ')}.</p><p><b>reviewed != share_approved</b></p></div>`; }
  function renderReports() { $('#reports').innerHTML = `<div class="panel"><h2>Reports</h2><p class="muted">Local export buttons call server-side export previews.</p><div class="row">${['html','csv','geojson','stix','misp'].map((f) => `<a class="btn" href="/api/reports/export?format=${f}" target="_blank">Export ${f.toUpperCase()}</a>`).join('')}</div></div>`; }
  function renderAdmin() { $('#admin').innerHTML = `<div class="panel"><h2>Admin Settings</h2><p class="muted">Connector configuration stays compact. Secrets remain backend-only references and are not exported.</p><div class="codebox">runtime/ingestion_candidates.json\nruntime/project_state.json\nruntime/audit_log.json\nruntime/legacy_import_log.json</div><h3>Legacy Import</h3><p class="muted">Supported: items.json, sources.json, claims.json, evidence.json and media manifests.</p></div>`; }
  async function runAll() { try { toast('Running candidate-only ingestion...'); const result = await api('/api/ingestion/run-all', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ limit_per_case: 40 }) }); state.candidates = result.candidates || []; renderAll(); toast(`Stored ${result.stored || state.candidates.length} candidate records`); } catch (err) { toast('Run-all failed: ' + err.message); } }
  document.addEventListener('click', async (e) => { const action = e.target.closest('[data-action]')?.dataset.action; if (action === 'run-all') await runAll(); if (action === 'refresh') { await loadData(); renderAll(); toast('Refreshed'); } const caseButton = e.target.closest('[data-case]'); if (caseButton) { state.activeCase = caseButton.dataset.case; renderOverview(); } });
  loadData().then(shell).catch((err) => { $('#app').innerHTML = `<pre>Failed to load LegoLens Core v3.0.0: ${esc(err.message)}</pre>`; });
})();
