(() => {
  const $ = (id) => document.getElementById(id);
  const safe = (v) => String(v ?? '').replace(/[&<>"']/g, (m) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const cases = [
    ['iran','Iran',476,382,476],
    ['sudan','Sudan',32,10,32],
    ['gaza-regional-spillover','Gaza Regional Spillover',32,10,32],
    ['ukraine-donbas','Ukraine Donbas',32,10,32],
    ['red-sea-yemen','Red Sea Yemen',32,10,32],
    ['sahel','Sahel',32,10,32]
  ];
  let candidates = JSON.parse(localStorage.getItem('legolens_v2_candidates') || '[]');
  const card = (title, body, cls='') => `<article class="v2-card ${cls}"><h3>${safe(title)}</h3>${body}</article>`;
  const thumbs = (n) => Array.from({length: 4}, (_, i) => `assets/thumb_${String(((n+i)%60)+1).padStart(3,'0')}.jpg`);
  function addCandidates(caseId='multi-case') {
    const now = new Date().toISOString();
    const add = Array.from({length: 6}, (_, i) => ({candidate_id:`cand_${caseId}_${Date.now()}_${i}`, case_id:caseId, title:`New ${caseId} content candidate ${i+1}`, status:'needs_review', retrieved_at:now}));
    candidates = [...add, ...candidates].slice(0,100);
    localStorage.setItem('legolens_v2_candidates', JSON.stringify(candidates));
    renderUpdates();
  }
  function renderOverview(){ const el=$('overview-hub'); if(!el) return; el.innerHTML=`<h2>LegoLens Core v2.0</h2><p class="v2-muted">Review-first intelligence platform voor multi-case monitoring, content acquisition en gecontroleerde uitwisseling.</p><div class="v2-grid">${card('Datasets','<div class="v2-kpi">6</div><p>Case packs met content, claims, evidence en graph metadata.</p><a class="btn" href="#datasets">Open Datasets</a>','v2-good')}${card('Content Updates','<div class="v2-kpi">candidate-only</div><p>Nieuwe content komt eerst in de review queue.</p><button class="btn btn-red" data-v2="check-updates">Check new content</button>')}${card('Ingestion','<div class="v2-kpi">connectors</div><p>Bronnen, connectoren, runs en update policies.</p><a class="btn" href="#ingestion-center">Open Ingestion</a>')}${card('Exchange','<div class="v2-kpi">STIX/TAXII/MISP</div><p>Sharing alleen na expliciete approval.</p><a class="btn" href="#exchange-center">Open Exchange</a>')}${card('Graph Stats','<div class="v2-kpi">analytics</div><p>Dataset coverage, nodes, edges en source mix.</p><a class="btn" href="#graph-dataset-stats">Open Graph Stats</a>')}</div>`; }
  function renderDatasets(){ const el=$('datasets'); if(!el) return; el.innerHTML=`<h2>Case Pack Datasets</h2><p class="v2-muted">Alle case packs zijn zichtbaar en bevatten startercontent.</p><div class="v2-grid">${cases.map((c,i)=>card(c[1],`<div class="v2-preview-row">${thumbs(i*7).map(src=>`<img src="${src}" alt="${safe(c[1])} preview">`).join('')}</div><table class="v2-table"><tr><th>Items</th><td>${c[2]}</td></tr><tr><th>Sources</th><td>${c[3]}</td></tr><tr><th>Evidence</th><td>${c[4]}</td></tr></table><button class="btn" data-v2="make-candidates" data-case="${c[0]}">Maak review candidates</button>`)).join('')}</div>`; const cd=$('case-dashboards'); if(cd) cd.innerHTML=`<h2>Case Dashboards</h2><div class="v2-grid">${cases.map((c,i)=>card(`${c[1]} dashboard`,`<div class="v2-preview-row">${thumbs(i*9+2).map(src=>`<img src="${src}" alt="${safe(c[1])}">`).join('')}</div><p>Dashboard met content previews, claims, bronnen, evidence coverage en graph samenvatting.</p>`)).join('')}</div>`; }
  function renderUpdates(){ const el=$('content-updates'); if(!el) return; el.innerHTML=`<h2>Content Update Center</h2><p class="v2-muted">Updateflow: ophalen → candidates → review → approved content.</p><div class="v2-grid">${card('Nieuwe content ophalen',`<p>Lokale candidates: <strong>${candidates.length}</strong></p><button class="btn btn-red" data-v2="check-updates">Check & import new content</button> <button class="btn" data-v2="clear-candidates">Clear local candidates</button>`,'v2-good')}${card('Transaction model','<ol><li>Check update</li><li>Normalize</li><li>Deduplicate</li><li>Policy check</li><li>Import as candidates</li><li>Audit log</li></ol>')}${card('Review queue', candidates.length ? `<table class="v2-table"><tr><th>Case</th><th>Title</th><th>Status</th></tr>${candidates.slice(0,12).map(c=>`<tr><td>${safe(c.case_id)}</td><td>${safe(c.title)}</td><td>${safe(c.status)}</td></tr>`).join('')}</table>` : '<p class="v2-muted">Geen lokale update candidates.</p>')}</div>`; }
  function renderIngestion(){ const el=$('ingestion-center'); if(el) el.innerHTML=`<h2>Ingestion Center</h2><div class="v2-grid">${card('Connector Registry','<span class="v2-pill">RSS</span> <span class="v2-pill">JSON</span> <span class="v2-pill">CSV</span> <span class="v2-pill">Manual URL</span><p>Alle connectoren schrijven candidate-only.</p>')}${card('Source Health','<p>Approval rate</p><div class="v2-bar"><span style="width:72%"></span></div><p>Duplicate rate</p><div class="v2-bar"><span style="width:18%"></span></div><p>Error rate</p><div class="v2-bar"><span style="width:4%"></span></div>')}${card('External Connections','<p>Configureer server-side templates voor ChatGPT/OpenAI, MISP, TAXII, STIX, RSS, JSON en CSV.</p><a class="btn" href="#external-connections">Open connections</a>')}</div>`; const ext=$('external-connections'); if(ext) ext.innerHTML=`<h2>External Connections</h2><div class="v2-grid">${['ChatGPT / OpenAI','MISP server','TAXII server','STIX file exchange','RSS feed','JSON feed','CSV importer'].map(name=>card(name,'<p class="v2-muted">Backend-only secrets. Frontend toont alleen configuratieprofiel en policy.</p><span class="v2-pill">candidate-only import</span>')).join('')}</div>`; }
  function renderExchange(){ const el=$('exchange-center'); if(!el) return; el.innerHTML=`<h2>Exchange Center</h2><p class="v2-muted">Reviewed is niet automatisch share-approved.</p><div class="v2-grid">${card('STIX / TAXII / MISP','<span class="v2-pill">STIX 2.1</span> <span class="v2-pill">TAXII 2.1</span> <span class="v2-pill">MISP</span><p>Import komt binnen als external candidates; export vereist share approval.</p>','v2-good')}${card('Extra standaarden','<p>CACAO, OpenC2, Sigma, YARA, CSAF, OSCAL, OCSF, MITRE ATT&CK, OpenAPI, GeoJSON, SPDX, CycloneDX.</p>')}${card('Sharing policy','<table class="v2-table"><tr><th>Status</th><td>internal_only / share_review_required / share_approved / shared / retracted</td></tr><tr><th>TLP</th><td>CLEAR, GREEN, AMBER, AMBER+STRICT, RED</td></tr></table>')}</div>`; }
  function renderGraph(){ const el=$('graph-dataset-stats'); if(!el) return; el.innerHTML=`<h2>Graph Dataset Statistics</h2><div class="v2-grid">${card('Dataset coverage','<div class="v2-kpi">668</div><p>Legacy + case-pack items</p><div class="v2-bar"><span style="width:88%"></span></div>')}${card('Sources','<div class="v2-kpi">442</div><p>Legacy + case-pack sources</p><div class="v2-bar"><span style="width:76%"></span></div>')}${card('Evidence','<div class="v2-kpi">668</div><p>Evidence records</p><div class="v2-bar"><span style="width:82%"></span></div>')}${card('Report coverage by type','<p>Monitoring Brief</p><div class="v2-bar"><span style="width:70%"></span></div><p>Evidence Appendix</p><div class="v2-bar"><span style="width:55%"></span></div><p>Source Reliability</p><div class="v2-bar"><span style="width:48%"></span></div>')}</div>`; }
  document.addEventListener('click', e => { const b=e.target.closest('[data-v2]'); if(!b) return; const a=b.getAttribute('data-v2'); if(a==='check-updates') addCandidates('multi-case'); if(a==='make-candidates') addCandidates(b.getAttribute('data-case') || 'case'); if(a==='clear-candidates'){ candidates=[]; localStorage.removeItem('legolens_v2_candidates'); renderUpdates(); }});
  function init(){ renderOverview(); renderDatasets(); renderUpdates(); renderIngestion(); renderExchange(); renderGraph(); }
  document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', init) : init();
})();
