import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const graph=JSON.parse(fs.readFileSync(path.join(root,'data','network_graph.json'),'utf8'));
const intel=JSON.parse(fs.readFileSync(path.join(root,'data','graph_intelligence_v120.json'),'utf8'));
const js=fs.readFileSync(path.join(root,'v116_overrides.js'),'utf8') + fs.readFileSync(path.join(root,'v120_overrides.js'),'utf8');
if (!graph.nodes?.length || !graph.edges?.length) throw new Error('network graph empty');
if (!intel.community_detection?.length) throw new Error('v120 graph intelligence missing communities');
if (!js.includes('renderToday') || !js.includes('graph_intelligence_v120')) throw new Error('v120 graph/workflow runtime not wired');
console.log('PASS graph explorer test');
