import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const read = f => JSON.parse(fs.readFileSync(path.join(root, 'data', f), 'utf8'));
const fail = [];
const version = read('version.json');
const manifest = read('release_manifest.json');
const gate = read('release_gate_v1_0.json');
const items = read('items.json');
const sources = read('sources.json');
const evidence = read('evidence.json');
const update = read('update_manifest.json');
if (version.release !== 'v1.0.0') fail.push('version.json release is not v1.0.0');
if (manifest.release !== version.release) fail.push('release manifest mismatch');
if (update.latest_release !== version.release) fail.push('update manifest latest_release mismatch');
if (gate.status !== 'pass') fail.push('release gate status not pass');
if (items.length !== 476) fail.push(`items count changed: ${items.length}`);
if (sources.length !== 382) fail.push(`sources count changed: ${sources.length}`);
if (evidence.length !== 476) fail.push(`evidence count changed: ${evidence.length}`);
for (const p of ['README.md','docs/PROJECT_OVERVIEW.md','docs/SYSTEM_EXPLANATION.md','docs/GITHUB_AND_CHATGPT_GUIDE.md','CONTRIBUTING.md','CODE_OF_CONDUCT.md','SECURITY.md','ETHICS.md','DATA_POLICY.md','RESPONSIBLE_USE.md','case-packs/iran/case.json']) if (!fs.existsSync(path.join(root,p))) fail.push('missing ' + p);
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
for (const req of ['v1_overrides.js','v1_overrides.css','data/bootstrap.js']) if (!html.includes(req)) fail.push(`index missing ${req}`);
const bootstrap = fs.readFileSync(path.join(root, 'data', 'bootstrap.js'), 'utf8');
if (!bootstrap.includes('release_gate_v1_0') || !bootstrap.includes('community_release_v1')) fail.push('bootstrap missing v1 data');
if (fail.length) { console.error('FAIL LegoLens v1 validation'); for (const f of fail) console.error('-', f); process.exit(1); }
console.log('PASS LegoLens v1.0 release validation');
